### ISSUE TITLE
Update to Node 6.x

### ISSUE THREAD

**Issue by panuhorsmalahti** [MartinsThiago/nvm-browsers#1]
To support newest Node.js features.

**Comment by LiberQuack** [comment]
Sure, I will try to update it today

**Comment by panuhorsmalahti** [comment]
I'm using the following:

```
FROM node:6
MAINTAINER Panu Horsmalahti <panu.horsmalahti@digia.com>

# Dockerfile based on https://github.com/MartinsThiago/polymer-tester

# Wct installation happens locally because https://github.com/Polymer/web-component-tester/issues/168

ENV DISPLAY=0:0
ENV PATH=$PATH:/node_modules/.bin

RUN apt-get -y update && \
    apt-get -y install curl && \
    apt-get -y install software-properties-common && \
    apt-get -y update && \
    apt-get -y install iceweasel xvfb openjdk-7-jre-headless

ENTRYPOINT ["/bin/bash", "-c", "npm install --loglevel warn && npm run install-and-build && xvfb-run npm run test"]
```

This worked fine until today, when selenium was updated, which requires openjdk 8. However, `openjdk-8-jre-headless` cannot be installed..

**Comment by LiberQuack** [comment]
Try using this ppa --> ppa:webupd8team/java

It's not the best solution once it install all the JDK... but should work

``` bash
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
printf "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo /usr/bin/debconf-set-selections
sudo apt-get -y install oracle-java8-installer
```

**Comment by LiberQuack** [comment]
Sorry, it's been quite a long time...

I upgraded nodejs and changed base image to `ubuntu:16.10` and remove a few things

So about your image... probably you already have fixed java8 issue, but anyway... I realized that node docker image is "based" on debian 8 and it doesn't have `openjdk-8-jre-headless` package
